server {
    listen 80;
    server_name _;
    client_max_body_size 0;

    # NPM: "Block Common Exploits"
    set $block_common 0;

    # NPM: "Cache Assets" (assets.conf) - note: no html in the list
    location ~* ^.*\.(css|js|jpe?g|gif|png|woff|woff2|eot|ttf|svg|ico|css\.map|js\.map)$ {
        proxy_pass http://rk-jf:8096;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Scheme $scheme;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        if_modified_since off;
        add_header Cache-Control "public, max-age=31536000, s-maxage=31536000, immutable";
        access_log off;
    }

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Scheme $scheme;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_pass http://rk-jf:8096;
    }
}
map $http_upgrade $http_connection { default upgrade; "" close; }
